In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk
import warnings
%matplotlib inline

warnings.filterwarnings("ignore")

In [37]:
#load datasets

df = pd.read_csv("tweets.csv", encoding="latin-1", names=["label", "id", "date", "query", "user", "tweet"])
df.head()

,label,id,date,query,user,tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600000 entries, 0 to 1599999
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   label   1600000 non-null  int64
 1   id      1600000 non-null  int64
 2   date    1600000 non-null  object
 3   query   1600000 non-null  object
 4   user    1600000 non-null  object
 5   tweet   1600000 non-null  object
dtypes: int64(2), object(4)
memory usage: 73.2+ MB

## Preprocessing datasets

In [39]:
#remove pattern in input text

def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    
    for word in r:
        input_txt = re.sub(word, "", input_txt)

    return input_txt

#remove twitter handles(@user)

df["clean_tweet"] = df["tweet"].apply(lambda x: remove_pattern(x, r"@[\w]*"))

In [40]:
df.head()

,label,id,date,query,user,tweet,clean_tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...","http://twitpic.com/2y1zl - Awww, that's a bum..."
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,I dived many times for the ball. Managed to s...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....","no, it's not behaving at all. i'm mad. why am..."

In [41]:
#remove special characters, num and punctuations

df["clean_tweet"] = df["clean_tweet"].str.replace("[^a-zA-Z#]", " ", regex = True)
df.head()

,label,id,date,query,user,tweet,clean_tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",http twitpic com y zl Awww that s a bum...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,is upset that he can t update his Facebook by ...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,I dived many times for the ball Managed to s...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",no it s not behaving at all i m mad why am...

In [42]:
#remove short words
df["clean_tweet"] = df["clean_tweet"].apply(lambda x: " ".join([w for w in x.split() if len(w)>2]))
df.head()

,label,id,date,query,user,tweet,clean_tweet
0,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t...",http twitpic com Awww that bummer You shoulda ...
1,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...,upset that can update his Facebook texting and...
2,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...,dived many times for the ball Managed save The...
3,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire,whole body feels itchy and like its fire
4,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all....",not behaving all mad why here because can see ...

In [43]:
# individual words considered as tokens
tokenized_tweet = df["clean_tweet"].apply(lambda x: x.split())
tokenized_tweet.head()

0    [http, twitpic, com, Awww, that, bummer, You, ...
1    [upset, that, can, update, his, Facebook, text...
2    [dived, many, times, for, the, ball, Managed, ...
3    [whole, body, feels, itchy, and, like, its, fire]
4    [not, behaving, all, mad, why, here, because, ...
Name: clean_tweet, dtype: object

## Exploratory Data Analysis

In [44]:
# extract the hashtag
def hashtag_extract(tweets):
    hashtags = []
    # Loop words in the tweet
    for tweet in tweets:
        ht = re.findall(r"#(\w+)", tweet)
        hashtags.append(ht)
    return hashtags

## Feature Extraction

In [52]:
#feature extraction

from sklearn.feature_extraction.text import TfidfVectorizer
bow_vectorizer = TfidfVectorizer(max_df = 0.90, min_df = 2, max_features = 50000, stop_words = "english")
bow = bow_vectorizer.fit_transform(df["clean_tweet"])

In [53]:
#split input for training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(bow, df["label"], random_state=42, test_size = 0.25)

## Model Training

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score

#training
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [56]:
#testing
pred = model.predict(x_test)
f1_score(y_test, pred, pos_label=4)

0.7811164435709265

In [57]:
accuracy_score(y_test, pred)

0.7750375

## Save the Trained Model and Vectorizer

In [58]:
import pickle

# save the model
pickle.dump(model, open("model.pkl", "wb"))

# save the vectorizer
pickle.dump(bow_vectorizer, open("vectorizer.pkl", "wb"))

## Model Summary

In [59]:
# final model performance

print("F1 Score:", f1_score(y_test, pred, pos_label=4))
print("Accuracy:", accuracy_score(y_test, pred))

F1 Score: 0.7811164435709265
Accuracy: 0.7750375